---
# roles/example/tasks/pre.yml
#- name: gather os specific variables
#  vars_files:
#    - "{{ansible_facts['distribution']}}-{{ansible_facts['distribution_major_version']}}.yml"


- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yaml'
      paths:
        - 'vars'
- debug:
    msg: "{{ package_name }}"

- name: "Downloading packages"
  package:
     name: "{{ package_name }}"
     state: present

- name: Stop Service
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ service_name }}"

- name: Importing settings
  include_tasks: "settings/pre.yml"

- name: "starting services"
  service:
     name: "{{ item }}"
     state: started
  with_items: "{{ service_name }}"

- name: Importing settings
  include_tasks: "settings/post.yml"
