---
# - name: Install MongoDB
#   apt:
#     pkg:
#       - mongodb-org-server
#       - mongodb-org-mongos
#       - mongodb-org-shell
#       - mongodb-org-tools 
#     state: latest
#     update_cache: true