---
- name: Install OpenLDAP for Fedora 8
  dnf:
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - sendmail-cf
    state: latest
    update_cache: true
  when: ansible_facts['lsb']['major_release'] | int >= 8