---
- name: Install OpenLDAP for RedHat 8
  dnf:
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - sendmail-cf
    state: latest
    update_cache: true
  when: ansible_facts['lsb']['major_release'] | int >= 8

- name: Install OpenLDAP for RedHat 7
  yum:
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - sendmail-cf
    state: latest
    update_cache: true
  when: ansible_facts['lsb']['major_release'] | int == 7

- name: Setup packages
  import_tasks: settings/main.yml
  vars:
    schema_location: /etc/openldap/schema

