---
- name: Install openldap
  ansible.builtin.dnf:
    name: "openldap"
    state: present

- name: Install openldap-servers
  ansible.builtin.dnf:
    name: "openldap-servers"
    state: present

- name: Install openldap-clients
  ansible.builtin.dnf:
    name: "openldap-clients"
    state: present

- name: Install sendmail-cf
  ansible.builtin.dnf:
    name: "sendmail-cf"
    state: present

- name: Setup packages
  import_tasks: settings/main.yml

