---
- name: Install openldap
  ansible.builtin.dnf:
    name: "openldap"
    state: present

- name: Install openldap-servers
  ansible.builtin.dnf:
    name: "openldap-servers"
    state: present

- name: Install openldap-clients
  ansible.builtin.dnf:
    name: "openldap-clients"
    state: present

- name: Install sendmail-cf
  ansible.builtin.dnf:
    name: "sendmail-cf"
    state: present

- name: Copying sendmail schema file to openldap.
  copy:
    src: "/usr/share/sendmail-cf/sendmail.schema"
    dest: "/etc/openldap/schema/mail.schema"

- name: create tmp directory
  tasks:
    - file:
      path: "/tmp/openldap"
      state: directory
    - file:
      path: "/tmp/ldif"
      state: directory

- name: copy tmp directory
  copy:
    src: "redhat/schema_conv.conf"
    dest: "/tmp/openldap/schema_conv.conf"

- name: merge schmea defines
  ansible.builtin.shell: <
    slaptest -f /tmp/openldap/schema_conv.conf -F /tmp/ldif/