---
- hosts: Ubuntu
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - name: get known_hosts fingerprint for ubuntu nodes
    command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
    register: keyscan

  - name: add ansible_host to known_hosts
    lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"

- hosts: CentOS
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - name: get known_hosts fingerprint for ubuntu nodes
    command: /usr/bin/ssh-keyscan -t rsa {{ ansible_host }}
    register: keyscan

  - name: add ansible_host to known_hosts
    known_hosts:
      name: "{{ ansible_host }}"
      key: "{{ item }}"
    with_items:
      - "{{ keyscan.stdout_lines }}"