- name: Copying sendmail schema file to openldap.
  copy:
    src: "/usr/share/sendmail-cf/sendmail.schema"
    dest: "{{schema_location}}/mail.schema"

- name: creating tmp directory
  file:
    path: "/tmp/openldap"
    state: directory
- name: creating tmp directory
  file:
    path: "/tmp/ldif"
    state: directory

- name: copy schema file
  template:
    src: "schema_conv.conf.j2"
    dest: "/tmp/openldap/schema_conv.conf"

- name: merge schmea defines
  shell:
    slaptest -f /tmp/openldap/schema_conv.conf -F /tmp/ldif/

- name: modifiy schema defines
  shell: |
    cp /tmp/ldif/cn=config/cn=schema/cn=\{[0-9]\}mail.ldif {{schema_location}}/mail.ldif
    sed -i s/dn:\ cn=\{\[0-9\]\}mail/dn:\ cn=mail,cn=schema,cn=config/g {{schema_location}}/mail.ldif
    sed -i s/cn:\ \{[0-9]\}mail/cn:\ mail/g {{schema_location}}/mail.ldif
    sed -i /structuralObjectClass/d {{schema_location}}/mail.ldif
    sed -i /creatorsName/d {{schema_location}}/mail.ldif
    sed -i /createTimestamp/d {{schema_location}}/mail.ldif
    sed -i /entryCSN/d {{schema_location}}/mail.ldif
    sed -i /modifiersName/d {{schema_location}}/mail.ldif
    sed -i /modifyTimestamp/d {{schema_location}}/mail.ldif

- name: add schema defines
  shell: |
    ldapadd -Q -Y EXTERNAL -H ldapi:/// -f {{schema_location}}/mail.ldif
